import type { CatInsert, CatMode, CatPublicView } from "../types.js";

/**
 * Insert a new cat.
 * public_id must be generated by the TypeScript ID generator before calling
 * this function. Throws a D1 UNIQUE constraint error if public_id is already
 * taken — the caller must catch and retry with a freshly generated public_id.
 * Internal cat.id is never returned; use public_id for all subsequent lookups.
 */
export async function insertCat(
  db: D1Database,
  data: CatInsert,
): Promise<void> {
  await db
    .prepare(
      `INSERT INTO cats (public_id, owner_id, name, country_code, photo_r2_key, current_mode)
       VALUES (?, ?, ?, ?, ?, ?)`,
    )
    .bind(
      data.public_id,
      data.owner_id,
      data.name,
      data.country_code,
      data.photo_r2_key ?? null,
      data.current_mode ?? "active",
    )
    .run();
}

/**
 * Look up a cat by public_id, verified to belong to the given owner.
 * Returns null if the cat does not exist or is not owned by this owner.
 * Used for owner dashboard pages where the public ID is known from the URL
 * but ownership must be confirmed before rendering private details.
 */
export async function getCatForOwner(
  db: D1Database,
  publicId: string,
  ownerId: number,
): Promise<CatPublicView | null> {
  return db
    .prepare(
      `SELECT public_id, name, country_code, photo_r2_key, current_mode
       FROM cats
       WHERE public_id = ? AND owner_id = ?`,
    )
    .bind(publicId, ownerId)
    .first<CatPublicView>();
}

/**
 * Public cat lookup — used on every QR scan.
 * Returns only whitelisted public columns. No internal id, no owner_id,
 * no cartilla data, no contact settings (fetch separately if needed for mode).
 * Returns null if no cat with that public_id exists.
 */
export async function getCatPublicProfile(
  db: D1Database,
  publicId: string,
): Promise<CatPublicView | null> {
  return db
    .prepare(
      `SELECT public_id, name, country_code, photo_r2_key, current_mode
       FROM cats
       WHERE public_id = ?`,
    )
    .bind(publicId)
    .first<CatPublicView>();
}

/**
 * List all cats belonging to an owner (owner dashboard).
 * Returns the same whitelisted public columns as getCatPublicProfile.
 * ownerId is an internal value from the authenticated session — never a URL param.
 */
export async function listCatsForOwner(
  db: D1Database,
  ownerId: number,
): Promise<CatPublicView[]> {
  const result = await db
    .prepare(
      `SELECT public_id, name, country_code, photo_r2_key, current_mode
       FROM cats
       WHERE owner_id = ?
       ORDER BY created_at ASC`,
    )
    .bind(ownerId)
    .all<CatPublicView>();
  return result.results;
}

/**
 * Update the active mode for a cat.
 * Only succeeds if public_id and owner_id both match, preventing one owner
 * from switching another owner's cat. Returns true if updated, false if the
 * cat was not found or not owned by this owner.
 */
export async function updateCatMode(
  db: D1Database,
  publicId: string,
  ownerId: number,
  mode: CatMode,
): Promise<boolean> {
  const result = await db
    .prepare(
      `UPDATE cats
       SET current_mode = ?
       WHERE public_id = ? AND owner_id = ?`,
    )
    .bind(mode, publicId, ownerId)
    .run();
  return result.meta.changes > 0;
}

/**
 * Update the R2 key for a cat's profile photo.
 * Only succeeds if ownership is confirmed. Returns true if updated.
 */
export async function updateCatPhoto(
  db: D1Database,
  publicId: string,
  ownerId: number,
  photoR2Key: string,
): Promise<boolean> {
  const result = await db
    .prepare(
      `UPDATE cats
       SET photo_r2_key = ?
       WHERE public_id = ? AND owner_id = ?`,
    )
    .bind(photoR2Key, publicId, ownerId)
    .run();
  return result.meta.changes > 0;
}
